--Adding IDENTITY column during table creation
Create table Contact
(
	firstName varchar (50) not null,
	lastName varchar (50) not null,
	contactId int not null IDENTITY (5, 2)
)

insert into contact values 
('One', 'A'),
('Two', 'B'),
('Three', 'C');

select * from Contact

DROP table Contact

--Adding IDENTITY by altering the table
Create table Contact
(
	firstName varchar (50) not null,
	lastName varchar (50) not null,
)

Alter table Contact
Add contactId int not null IDENTITY (5, 2)

insert into contact values 
('One', 'A'),
('Two', 'B'),
('Three', 'C');

select * from Contact

DROP table Contact

--Adding an IDENTITY Column by altering a table after a bunch of inserts into the table
Create table Contact
(
	firstName varchar (50) not null,
	lastName varchar (50) not null,
)

insert into contact values 
('One', 'A'),
('Two', 'B'),
('Three', 'C');

Alter table Contact
Add contactId int not null IDENTITY (5, 2)

select * from Contact


--IDENT_CURRENT(tablename) provides the last value generated, regardless of the connection or scope it was created on.
select IDENT_CURRENT ('Contact')

--It is often useful or necessary to know what identity value was generated by an INSERT command. @@IDENTITY provides the last value generated on the current connection in the current scope, 
Insert into Contact values ('Four', 'C')
select @@IDENTITY
